# Generated by Django 4.2.1 on 2026-05-10 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wishlistapp', '0002_memory'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemoryPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Upload a photo from this memory', upload_to='memory_photos/')),
                ('caption', models.CharField(blank=True, help_text='Optional caption for the photo', max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('memory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='wishlistapp.memory')),
            ],
        ),
    ]
